apiVersion: inference.networking.k8s.io/v1
kind: InferencePool
metadata:
  name: vllm-smol
  namespace: default
spec:
  targetPorts:
    - number: 8000
  selector:
    matchLabels:
      app: vllm-smol
  endpointPickerRef:
    name: vllm-smol-epp
    port:
      number: 9002
